version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: kyoenji_wordpress
      MYSQL_USER: kyoenji_admin
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    volumes:
      - wp-content:/var/www/html/wp-content
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db_data:
  wp-content:
  caddy_data:
  caddy_config:
